version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - postgres
    ports:
      - "8098:8098"
    # Эти свойства перегружают соответствующие в application.yml
    environment:
      - SPRING_H2_CONSOLE_ENABLED=false
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_DATA_LOCATIONS=classpath:data.sql
    networks:
      - nw
  postgres:
    # В идеале должна быть ещё и версия image
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library
    networks:
      - nw
networks:
  nw:
