spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations: classpath:data-local.sql
      schema-locations: classpath:schema.sql
      mode: embedded
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8098

jwt:
  secret: FfbEDyJ0s5qEqyMQyJ0u
  issuer: libraryJwt
  expiration-time: 86400
  refresh-expiration-time: 172800
