spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    rest:
      base-path: /datarest

server:
  port: 8098


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
  info:
    git:
      mode: full

info:
  version: @project.version@
  author: Alexander Mikheev
  descriptiion: Library Application

logging:
  file:
    name: library.log
  level:
    root: warn
    org:
      springframework:
        web: debug
      hibernate: info
